### PR TITLE
fix(OculusHeadset): include latest GearVR revision

### PR DESCRIPTION
**Pull request by prashant-naidu**

### CODE REVIEW

**Comment by kristianpd** [comment]
You'll need to update the commit message to get it merged:

> chore(SDK_OculusHeadset): include latest GearVR version

maybe?

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: be6459cbce59f2a6770793233ef43eae265832c2
  * Your subject line is longer than 72 characters

Guidelines are available at https://github.com/thestonefox/SteamVR_Unity_Toolkit

---
This message was auto-generated by https://gitcop.com

**Comment by mattboy64** [comment]
Could you add the Go in as well?

```
	public enum SystemHeadset
	{
		None = 0,
		GearVR_R320, // Note4 Innovator
		GearVR_R321, // S6 Innovator
		GearVR_R322, // Commercial 1
		GearVR_R323, // Commercial 2 (USB Type C)
		GearVR_R324, // Commercial 3 (USB Type C)
		GearVR_R325, // Commercial 4 (USB Type C)
		Oculus_Go,

		Rift_DK1 = 0x1000,
		Rift_DK2,
		Rift_CV1,
	}```

**Comment by thestonefox** [comment]
Does anyone want to re-do this PR with the additional headsets suggested by @mattboy64 ?

**Comment by thestonefox** [comment]
No longer merge-able with the new master branch. Closing.

**Pull request closed without merging**
