### PR TITLE
feat(Interaction): select objects by distance from attach point

### PR DESCRIPTION
**Pull request by RunenGamer**
Adds the multiTouchSelectionStyle option to VRTK_InteractTouch
(see #315 and #1618). Solves #1694 as well.
Allows user to specify which interactable will be
selected, when the controller is over multiple objects. The
existing style selects the most recently touched object.
This commit adds the ClostestOrigin style, which selects the
object with the closest origin to the controller attach point.

### CODE REVIEW

**Comment by RunenGamer** [comment]
@thestonefox : On #1618 you said, before you can merge, this feature needs to be tested by the community. Is there a common practise to gather someone for testing this feature or something I can to do? Is there a "needs to be tested by community" label?

**Comment by thestonefox** [comment]
I think a "Requires Community Testing/Approval" label is probably a good idea.

We're close to releasing 3.3.0, so after that I'll add a new label

**Comment by RunenGamer** [comment]
@thestonefox : Thank you. After 3.3.0 release: Please add the new to come "Requires Community Testing/Approval" label to this PR.

**Comment by thestonefox** [comment]
No longer merge-able with the new master branch. Closing.

**Pull request closed without merging**
